// webapp/src/components/Countdown.vue
<template>
    <div>
        <format-number
            :time="true"
            :value="remaining"
            v-if="remaining > 0"
        />

        <n-tag
            type="success"
            v-else="remaining === 0"
        >
            Done
        </n-tag>
    </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, toNative } from 'vue-facing-decorator';

import { NCountdown, NTag } from 'naive-ui';
import FormatNumber from '@/components/FormatNumber.vue';

@Component({
    components: {
        NCountdown,
        NTag,

        FormatNumber,
    }
})
class Countdown extends Vue {
    @Prop({
        type: String,
        required: true,
    })
    public endDate!: string;

    public remaining: number = 0;
    private intervalId!: number;

    public mounted() {
        this.updateTime();

        this.intervalId = setInterval(() => {
            this.updateTime();
        }, 1000);
    }

    public unmounted() {
        clearInterval(this.intervalId);
    }

    private updateTime() {
        // Typescript hates calculating dates
        const start: any = new Date();
        const end: any = new Date(this.endDate);
        const remaining = Math.floor((end - start) / 1000);
        this.remaining = remaining > 0 ? remaining : 0;
    }
}

export default toNative(Countdown);
</script>

// webapp_components/src/misc/Countdown.tsx
import { formatTime } from "../utils";
import { BadgeWrapper } from "../wrapper/Badge";
import { useEffect, useState } from "react";

export function Countdown({
    endDate
}: CountdownProps) {
    const [remaining, setRemaining] = useState(0);

    const updateTime = () => {
        const start: any = new Date();
        const end: any = new Date(endDate + 'Z');
        const remaining = Math.floor((end - start) / 1000);

        setRemaining(remaining > 0 ? remaining : 0);
    }

    useEffect(() => {
        updateTime();

        setInterval(() => {
            updateTime();
        }, 1000);
    }, []);

    if (remaining > 0) {
        return <>
            { formatTime(remaining) }
        </>
    } else {
        return <>
            <BadgeWrapper
                color="green.9"
            >
                Done
            </BadgeWrapper>
        </>
    }
}

export type CountdownProps = {
    endDate: string,
}
